# Generated by Django 4.2.3 on 2023-07-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_client_mailings_mailing_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='last_run',
            field=models.DateField(blank=True, null=True, verbose_name='дата последней отправки рассылки'),
        ),
    ]
