# Generated by Django 4.2.3 on 2023-07-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_mailing_last_run'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='server_code',
            field=models.CharField(blank=True, null=True, verbose_name='Ответ сервера'),
        ),
    ]
