# Generated by Django 4.2.3 on 2023-07-15 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_attempt_server_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'ordering': ('name',), 'permissions': [('deactivate_mailing', 'Deactivate_mailing')], 'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
    ]
