# Generated by Django 4.2.3 on 2023-07-17 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_mailing_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='server_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ответ сервера'),
        ),
    ]
